### ISSUE TITLE
Add accommodation model

### ISSUE THREAD

**Issue by timobrembeck** [digitalfabrik/coldaid-backend#1]
Add a model for accommodations, which should inherit all attributes of points of interest plus the following attributes:

- institution (Träger) - possibly foreign key to organization
- rules of the accommodation

- information about beds can be obtained by a reverse foreign key from the beds model.

**Comment by timobrembeck** [comment]
Things to consider: Do we need a dedicated bed model, or should we integrate this into the accommodation model?

**Comment by tailoric** [comment]
Question about the institution (Träger) 

what kind of model is that supposed to be, is it an account or an organization or just a string field?

**Comment by timobrembeck** [comment]
At first, I thought about just using a string field, but yes, we could also use a foreign key to the organization model. I like this idea actually.

**Comment by tailoric** [comment]
- For the rules use a subclass of POITranslation as a new model that has the rules in multiple languages.

- Beds are a ManyToOne relationship with accommodation 

- The institution (Träger) will be a foreign key to an organization

**Comment by tailoric** [comment]
Currently encountering a problem (not 100% if it is a problem though)
if I make AccommodationTranslation a subclass of POITranslation then it will inherit the poi foreign key since Accommodations inherit from POI they are also found in the POI list when trying to add models via the admin page. 
But this means a AccommodationTranslation will also be able to be attached to a POIs not only Accommodations.
So I feel like we need to handle this within code when adding Accommodations and their translations

**Comment by timobrembeck** [comment]
Actually, I think this is indeed a problem we haven't thought of.
I just tested it and the Foreign Key to POIs only accepts true POIs, no Accommodations. And in Django we cannot override attributes of parent models. So I think we can't inherit from POITranslation here, but have to copy it and make a complete new model.

**Comment by timobrembeck** [comment]
Additional fields needed:
`phone_number`
`mobile_number`
`wc_available`
`shower_available`
`animals_allowed`
`spoken_languages`

**Comment by tailoric** [comment]
Additional fields:
`intake_from`
`intake_to`
