### ISSUE TITLE
Check for GPS functionality

### ISSUE THREAD

**Issue by ulliholtgrave** [digitalfabrik/coldaid-backend#45]
A certain GPS functionality has been implemented, but the correctness has to be validated. If the feature isn't working accordingly, the feature has be refactored.

**Comment by LocoVIB** [comment]
The refactoring of the map feature has given the following insights:

1. The map (leaflet) used in this project uses the Geolocation API to locate user. It is important to distinguish whether the cleint runs on a mobile phone or not, because the location for mobile phones can be determined much more precisely. For all other devices only the IP address can be used, which leads to an approximated location within a certain radius.
2. Modern browsers do not allow location requests from unsecured websites. To demonstrate the prototype, the application should be accessible via https. For testing purposes chrome allows location requests on localhost.

To review the current location accuracy check out the branch `responsive-ui` if [issue 44](https://github.com/digitalfabrik/coldaid-backend/issues/44) is not closed and do a local test on chrome.
